### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by SeekPoint** [AKSW/KG2Vec#2]
```bash
mldl@ub1604:~/ub16_prj/KG2Vec$ sh kg2vec_analogy.sh aksw-bib AKSW-bib/aksw-bib.train+valid.nt 10 AKSW-bib/aksw-bib.test.nt
KG2Vec: dataset_id=aksw-bib training_data=AKSW-bib/aksw-bib.train+valid.nt dimensions=10 test_data=AKSW-bib/aksw-bib.test.nt verbalization_type= scoring=analogy
Using TensorFlow backend.
2018-08-22 15:35:09,441 : INFO : 'pattern' package not found; tag filters are not available for English
2018-08-22 15:35:09,443 : INFO : running train_model.py aksw-bib_.txt 10
2018-08-22 15:35:09,443 : WARNING : consider setting layer size to a multiple of 4 for greater performance
2018-08-22 15:35:09,443 : INFO : collecting all words and their counts
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/word2vec.py", line 1539, in __iter__
    self.source.seek(0)
AttributeError: 'str' object has no attribute 'seek'
```

During handling of the above exception, another exception occurred:

```bash
Traceback (most recent call last):
  File "train_model.py", line 22, in <module>
    learn(sys.argv[1], sys.argv[1] + '.w2v', int(sys.argv[2]))
  File "train_model.py", line 16, in learn
    model = Word2Vec(LineSentence(inp), size=int(size), window=3, sample=0, negative=5, min_count=1, workers=multiprocessing.cpu_count())
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/word2vec.py", line 503, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/word2vec.py", line 577, in build_vocab
    self.scan_vocab(sentences, progress_per=progress_per, trim_rule=trim_rule)  # initial survey
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/word2vec.py", line 589, in scan_vocab
    for sentence_no, sentence in enumerate(sentences):
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/word2vec.py", line 1548, in __iter__
    with utils.smart_open(self.source) as fin:
  File "/usr/local/lib/python3.5/dist-packages/smart_open/smart_open_lib.py", line 181, in smart_open
    fobj = _shortcut_open(uri, mode, **kw)
  File "/usr/local/lib/python3.5/dist-packages/smart_open/smart_open_lib.py", line 287, in _shortcut_open
    return io.open(parsed_uri.uri_path, mode, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'aksw-bib_.txt'
  File "analogy_predict.py", line 66
    for key, value in sorted(occur.iteritems(), key=lambda (k,v): (v,k), reverse=True)[:20]:
                                                           ^
SyntaxError: invalid syntax
mldl@ub1604:~/ub16_prj/KG2Vec$ 
```

**Comment by mommi84** [comment]
Hi,

there was a missing parameter (i.e., `output`) in the readme example. The right command line is:

```bash
sh kg2vec_analogy.sh aksw-bib aksw-bib-train+valid.nt 10 aksw-bib-test.nt output
```

Make sure you are using gensim version 2.1.0.

**Comment by SeekPoint** [comment]
```bash
mldl@ub1604:~/ub16_prj/KG2Vec$ sh kg2vec_analogy.sh aksw-bib AKSW-bib/aksw-bib.train+valid.nt 10 AKSW-bib/aksw-bib.test.nt output .
KG2Vec: dataset_id=aksw-bib training_data=AKSW-bib/aksw-bib.train+valid.nt dimensions=10 test_data=AKSW-bib/aksw-bib.test.nt verbalization_type=output scoring=analogy
2018-08-30 09:51:47,684 : INFO : 'pattern' package not found; tag filters are not available for English
2018-08-30 09:51:47,686 : INFO : running train_model.py aksw-bib_output.txt 10
2018-08-30 09:51:47,686 : WARNING : consider setting layer size to a multiple of 4 for greater performance
2018-08-30 09:51:47,686 : INFO : collecting all words and their counts
2018-08-30 09:51:47,686 : INFO : PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
2018-08-30 09:51:47,692 : INFO : collected 954 word types from a corpus of 8262 raw words and 2754 sentences
2018-08-30 09:51:47,692 : INFO : Loading a fresh vocabulary
2018-08-30 09:51:47,695 : INFO : min_count=1 retains 954 unique words (100% of original 954, drops 0)
2018-08-30 09:51:47,695 : INFO : min_count=1 leaves 8262 word corpus (100% of original 8262, drops 0)
2018-08-30 09:51:47,697 : INFO : deleting the raw counts dictionary of 954 items
2018-08-30 09:51:47,697 : INFO : sample=0 downsamples 0 most-common words
2018-08-30 09:51:47,697 : INFO : downsampling leaves estimated 8262 word corpus (100.0% of prior 8262)
2018-08-30 09:51:47,697 : INFO : estimated required memory for 954 words and 10 dimensions: 553320 bytes
2018-08-30 09:51:47,699 : INFO : resetting layer weights
2018-08-30 09:51:47,706 : INFO : training model with 8 workers on 954 vocabulary and 10 features, using sg=0 hs=0 sample=0 negative=5 window=3
2018-08-30 09:51:47,750 : INFO : worker thread finished; awaiting finish of 7 more threads
2018-08-30 09:51:47,750 : INFO : worker thread finished; awaiting finish of 6 more threads
2018-08-30 09:51:47,750 : INFO : worker thread finished; awaiting finish of 5 more threads
2018-08-30 09:51:47,756 : INFO : worker thread finished; awaiting finish of 4 more threads
2018-08-30 09:51:47,760 : INFO : worker thread finished; awaiting finish of 3 more threads
2018-08-30 09:51:47,762 : INFO : worker thread finished; awaiting finish of 2 more threads
2018-08-30 09:51:47,766 : INFO : worker thread finished; awaiting finish of 1 more threads
2018-08-30 09:51:47,766 : INFO : worker thread finished; awaiting finish of 0 more threads
2018-08-30 09:51:47,767 : INFO : training on 41310 raw words (41310 effective words) took 0.1s, 708208 effective words/s
2018-08-30 09:51:47,767 : WARNING : under 10 jobs per worker: consider setting a smaller `batch_words' for smoother alpha decay
2018-08-30 09:51:47,767 : INFO : precomputing L2-norms of word weight vectors
2018-08-30 09:51:47,773 : INFO : storing 954x10 projection weights into aksw-bib_output.txt.w2v
  File "analogy_predict.py", line 66
    for key, value in sorted(occur.iteritems(), key=lambda (k,v): (v,k), reverse=True)[:20]:
                                                           ^
SyntaxError: invalid syntax
mldl@ub1604:~/ub16_prj/KG2Vec$ 
```

**Comment by mommi84** [comment]
It seems like an indentation parsing problem. Which platform are you using?

The code is working perfectly on:

- macOS Sierra 10.12.6
- Ubuntu 16.04.5 LTS

**Comment by SeekPoint** [comment]
it works on python2.x

**Comment by iamaziz** [comment]
Tuple parameter unpacking in this line is not supported in Python3: https://github.com/AKSW/KG2Vec/blob/dea9e8baa5db523fd82d43014729d51bfe56093e/analogy_predict.py#L66

I think changing it to something like this should solve the issue:

```python
for key, value in sorted(occur.items(), key=lambda kv: (kv[1],kv[0]), reverse=True)[:20]:
```

**Comment by iamaziz** [comment]
https://github.com/AKSW/KG2Vec/issues/2#issuecomment-417022088

@mommi84 please notice the `sh` command has a small typo in the file names, uses `-` instead of `.`

TYPO:
```bash
aksw-bib-train+valid.nt 10 aksw-bib-test.nt
```
FIX
```bash
aksw-bib.train+valid.nt 10 aksw-bib.test.nt
```
